# Tests

test-selected:
	clear
	@make spacer
	make -f makefile.test test-receive-from-transport
	@make spacer
	make -f makefile.test test-classify-item
	@make spacer
	make -f makefile.test test-classify-item

## Warehouse

test-receive-from-transport:
	mix test ./test/ledger/warehouse/warehouse_test.exs:7

test-classify-item:
	mix test ./test/ledger/warehouse/warehouse_test.exs:26

test-relocate-in-store:
	mix test ./test/ledger/warehouse/warehouse_test.exs:57
